/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as RegisterRouteImport } from './app/routes/register'
import { Route as MycartRouteImport } from './app/routes/mycart'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as HomeRouteImport } from './app/routes/home'
import { Route as FavoritesRouteImport } from './app/routes/favorites'
import { Route as EmployeesRouteImport } from './app/routes/employees'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as StatisticsSectionRouteImport } from './app/routes/statistics.$section'
import { Route as ProductIdRouteImport } from './app/routes/product.$id'
import { Route as CategoryCategoryRouteImport } from './app/routes/category.$category'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MycartRoute = MycartRouteImport.update({
  id: '/mycart',
  path: '/mycart',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsSectionRoute = StatisticsSectionRouteImport.update({
  id: '/statistics/$section',
  path: '/statistics/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employees': typeof EmployeesRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mycart': typeof MycartRoute
  '/register': typeof RegisterRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/product/$id': typeof ProductIdRoute
  '/statistics/$section': typeof StatisticsSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employees': typeof EmployeesRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mycart': typeof MycartRoute
  '/register': typeof RegisterRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/product/$id': typeof ProductIdRoute
  '/statistics/$section': typeof StatisticsSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employees': typeof EmployeesRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mycart': typeof MycartRoute
  '/register': typeof RegisterRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/product/$id': typeof ProductIdRoute
  '/statistics/$section': typeof StatisticsSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employees'
    | '/favorites'
    | '/home'
    | '/login'
    | '/mycart'
    | '/register'
    | '/category/$category'
    | '/product/$id'
    | '/statistics/$section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/employees'
    | '/favorites'
    | '/home'
    | '/login'
    | '/mycart'
    | '/register'
    | '/category/$category'
    | '/product/$id'
    | '/statistics/$section'
  id:
    | '__root__'
    | '/'
    | '/employees'
    | '/favorites'
    | '/home'
    | '/login'
    | '/mycart'
    | '/register'
    | '/category/$category'
    | '/product/$id'
    | '/statistics/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeesRoute: typeof EmployeesRoute
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MycartRoute: typeof MycartRoute
  RegisterRoute: typeof RegisterRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  ProductIdRoute: typeof ProductIdRoute
  StatisticsSectionRoute: typeof StatisticsSectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mycart': {
      id: '/mycart'
      path: '/mycart'
      fullPath: '/mycart'
      preLoaderRoute: typeof MycartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics/$section': {
      id: '/statistics/$section'
      path: '/statistics/$section'
      fullPath: '/statistics/$section'
      preLoaderRoute: typeof StatisticsSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeesRoute: EmployeesRoute,
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MycartRoute: MycartRoute,
  RegisterRoute: RegisterRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  ProductIdRoute: ProductIdRoute,
  StatisticsSectionRoute: StatisticsSectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
